### ISSUE TITLE
Document changes from PR #3

### ISSUE THREAD

**Issue by lorisleiva** [lorisleiva/javel#6]
- One small section at the end of the README explaining how to add mixins that have dependencies in Javel.
- For each mixins that have external dependencies, add in their documentation page how to register the dependency itself.

<img width="951" alt="Screenshot 2019-03-13 at 09 41 48" src="https://user-images.githubusercontent.com/3642397/54269060-7dc38800-4574-11e9-855f-55c7cadfe384.png">

**Comment by lorisleiva** [comment]
Hi @hivokas,

I've updated the README and wrote the template for the [documentation of IntegratesQueryBuilder](https://github.com/lorisleiva/javel/blob/master/docs/IntegratesQueryBuilder.md).

Over to you. 🙂

**Comment by hivokas** [comment]
Done #7

**Comment by lorisleiva** [comment]
Perfect, thanks. I tagged a new release.
