### ISSUE TITLE
How to reset model?

### ISSUE THREAD

**Issue by nguyentranchung** [lorisleiva/javel#8]
I have init model

```js
    attribute: new Attribute({
      options: [],
      values: {}
    }),
```

After save with: this.attribute.save();  I want to reset to default. How can I do it?

**Comment by lorisleiva** [comment]
Hi there 👋 

You can use the `afterRequest` method for that.

```js
afterRequest (response, request) {

    // Custom logic here...

    return super.afterRequest(response, request)
}
```

Alternatively, if you only need to reset when using the `save` method, you can override it.

```js
save (attributes = null, configs = {}) {
    const model = super.save(attributes, configs)

    // Custom logic here...

    return model
}
```

I hope this helps.
